name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI"

      - name: Run tests
        run: bash test/run.sh
